[package]
name = "rust-sdl2-practice"
version = "0.1.0"
authors = ["Changseo-Jang <changseo.jang@riiid.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
